extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
  node: true
  es6: true
  jest: true
rules:
  react/prefer-stateless-function:
    - 0
  no-multi-spaces:
    - 0
  max-len:
    - 1
    - 200
    - 4
  react/no-multi-comp:
    - 0
  react/prop-types:
    - 0
